// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreData;
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSFetchedResultsController;
@class UICollectionView;
@protocol NSFetchedResultsSectionInfo;
@class NSIndexPath;
@class UICollectionViewLayout;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC17LCYCoreDataHelper14LCYCoreDataCVC")
@interface LCYCoreDataCVC : UICollectionViewController <NSFetchedResultsControllerDelegate>
@property (nonatomic, strong) NSFetchedResultsController * _Null_unspecified frc;
- (BOOL)performFetchAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (void)controller:(NSFetchedResultsController * _Nonnull)controller didChangeSection:(id <NSFetchedResultsSectionInfo> _Nonnull)sectionInfo atIndex:(NSInteger)sectionIndex forChangeType:(NSFetchedResultsChangeType)type;
- (void)controller:(NSFetchedResultsController * _Nonnull)controller didChangeObject:(id _Nonnull)anObject atIndexPath:(NSIndexPath * _Nullable)indexPath forChangeType:(NSFetchedResultsChangeType)type newIndexPath:(NSIndexPath * _Nullable)newIndexPath;
- (nonnull instancetype)initWithCollectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LCYCoreDataHelper25LCYCoreDataCollectionView")
@interface LCYCoreDataCollectionView : UICollectionView <NSFetchedResultsControllerDelegate>
@property (nonatomic, strong) NSFetchedResultsController * _Null_unspecified frc;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (BOOL)performFetchAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (NSInteger)numberOfSections;
- (NSInteger)numberOfItemsInSection:(NSInteger)section;
- (void)controller:(NSFetchedResultsController * _Nonnull)controller didChangeSection:(id <NSFetchedResultsSectionInfo> _Nonnull)sectionInfo atIndex:(NSInteger)sectionIndex forChangeType:(NSFetchedResultsChangeType)type;
- (void)controller:(NSFetchedResultsController * _Nonnull)controller didChangeObject:(id _Nonnull)anObject atIndexPath:(NSIndexPath * _Nullable)indexPath forChangeType:(NSFetchedResultsChangeType)type newIndexPath:(NSIndexPath * _Nullable)newIndexPath;
@end

@class NSManagedObjectContext;
@class NSURL;

SWIFT_CLASS("_TtC17LCYCoreDataHelper17LCYCoreDataHelper")
@interface LCYCoreDataHelper : NSObject <UIAlertViewDelegate>
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable selectedUniqueAttributes;
@property (nonatomic, readonly, strong) NSManagedObjectContext * _Nonnull parentContext;
@property (nonatomic, readonly, strong) NSManagedObjectContext * _Nonnull context;
@property (nonatomic, readonly, strong) NSManagedObjectContext * _Nonnull sourceContext;
@property (nonatomic, readonly, strong) NSManagedObjectContext * _Nonnull importContext;
@property (nonatomic, readonly, strong) NSManagedObjectContext * _Nonnull seedContext;
- (nullable instancetype)initWithStoreFileName:(NSString * _Nonnull)storeFileName sourceStoreFileName:(NSString * _Nullable)sourceStoreFileName entitiesToCopy:(NSArray<NSString *> * _Nullable)entitiesToCopy selectedUniqueAttributes:(NSDictionary<NSString *, NSString *> * _Nullable)selectedUniqueAttributes error:(NSError * _Nullable * _Null_unspecified)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)loadSourceStoreAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)setupCoreDataAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)deepCopyFromSourceStoreAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)deepCopyFromPersistentStore:(NSURL * _Nonnull)url error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)saveContextAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)backgroundSaveContextAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSString *, id> * _Nullable)change context:(void * _Null_unspecified)context;
- (BOOL)resetStoreAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
@end

@class NSPredicate;
@class NSPersistentStoreCoordinator;
@class NSPersistentStore;

@interface LCYCoreDataHelper (SWIFT_EXTENSION(LCYCoreDataHelper))
- (NSArray * _Nonnull)fetchAllCoreDataModels:(NSString * _Nonnull)entityName sortKey:(NSString * _Nonnull)sortKey ascending:(BOOL)ascending ctx:(NSManagedObjectContext * _Nonnull)ctx;

/// Removes all entities from within the specified NSManagedObjectContext excluding a supplied array of entities.
///
/// \param context The <code>NSManagedObjectContext
/// </code> to remove the Entities from.
- (BOOL)deleteAllExistingObjectOfEntity:(NSString * _Nonnull)entityName ctx:(NSManagedObjectContext * _Nonnull)ctx error:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)deleteAllMachingPredicate:(NSString * _Nonnull)entityName predicate:(NSPredicate * _Nonnull)predicate ctx:(NSManagedObjectContext * _Nonnull)ctx error:(NSError * _Nullable * _Null_unspecified)error;
- (void)resetContext:(NSManagedObjectContext * _Nonnull)moc;
- (BOOL)reloadStore;
- (void)removeAllStoresFromCoordinator:(NSPersistentStoreCoordinator * _Nonnull)psc;
- (void)resetCoreData;
- (BOOL)unloadStore:(NSPersistentStore * _Nullable)ps;
- (void)removeFileAtURL:(NSURL * _Nonnull)url;
@end

@class NSNotification;
@class UIAlertView;

@interface LCYCoreDataHelper (SWIFT_EXTENSION(LCYCoreDataHelper))
- (NSURL * _Nullable)iCloudStoreURL;
- (BOOL)iCloudAccountIsSignedIn;
- (void)listenForStoreChanges;
- (void)storesWillChange:(NSNotification * _Nonnull)n;
- (void)storesDidChange:(NSNotification * _Nonnull)n;
- (void)persistentStoreDidImportUbiquitiousContentChanges:(NSNotification * _Nonnull)n;
- (BOOL)iCloudEnabledByUser;
- (void)confirmMergeWithiCloud;
- (void)alertView:(UIAlertView * _Nonnull)alertView clickedButtonAtIndex:(NSInteger)buttonIndex;
- (BOOL)mergeNoniCloudDataWithiCloudAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (void)somethingChanged;
- (BOOL)loadNoniCloudStoreAsSeedStore;
- (void)destroyAlliCloudDataForThisApplication;
@end

@class UITableView;

SWIFT_CLASS("_TtC17LCYCoreDataHelper14LCYCoreDataTVC")
@interface LCYCoreDataTVC : UITableViewController <NSFetchedResultsControllerDelegate>
@property (nonatomic, strong) NSFetchedResultsController * _Null_unspecified frc;
- (void)performFetch;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView sectionForSectionIndexTitle:(NSString * _Nonnull)title atIndex:(NSInteger)index;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section;
- (NSArray<NSString *> * _Nullable)sectionIndexTitlesForTableView:(UITableView * _Nonnull)tableView;
- (void)controllerWillChangeContent:(NSFetchedResultsController * _Nonnull)controller;
- (void)controllerDidChangeContent:(NSFetchedResultsController * _Nonnull)controller;
- (void)controller:(NSFetchedResultsController * _Nonnull)controller didChangeSection:(id <NSFetchedResultsSectionInfo> _Nonnull)sectionInfo atIndex:(NSInteger)sectionIndex forChangeType:(NSFetchedResultsChangeType)type;
- (void)controller:(NSFetchedResultsController * _Nonnull)controller didChangeObject:(id _Nonnull)anObject atIndexPath:(NSIndexPath * _Nullable)indexPath forChangeType:(NSFetchedResultsChangeType)type newIndexPath:(NSIndexPath * _Nullable)newIndexPath;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LCYCoreDataHelper20LCYCoreDataTableView")
@interface LCYCoreDataTableView : UITableView <NSFetchedResultsControllerDelegate>
@property (nonatomic, strong) NSFetchedResultsController * _Null_unspecified frc;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)performFetch;
- (NSInteger)numberOfRowsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInTableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView sectionForSectionIndexTitle:(NSString * _Nonnull)title atIndex:(NSInteger)index;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section;
- (NSArray<NSString *> * _Nullable)sectionIndexTitlesForTableView:(UITableView * _Nonnull)tableView;
- (void)controllerWillChangeContent:(NSFetchedResultsController * _Nonnull)controller;
- (void)controllerDidChangeContent:(NSFetchedResultsController * _Nonnull)controller;
- (void)controller:(NSFetchedResultsController * _Nonnull)controller didChangeSection:(id <NSFetchedResultsSectionInfo> _Nonnull)sectionInfo atIndex:(NSInteger)sectionIndex forChangeType:(NSFetchedResultsChangeType)type;
- (void)controller:(NSFetchedResultsController * _Nonnull)controller didChangeObject:(id _Nonnull)anObject atIndexPath:(NSIndexPath * _Nullable)indexPath forChangeType:(NSFetchedResultsChangeType)type newIndexPath:(NSIndexPath * _Nullable)newIndexPath;
@end


SWIFT_CLASS("_TtC17LCYCoreDataHelper21LCYSoureceStoreHelper")
@interface LCYSoureceStoreHelper : NSObject
@property (nonatomic, readonly, strong) NSManagedObjectContext * _Nonnull sourceContext;
- (nullable instancetype)initWithSourceStoreFileName:(NSString * _Nonnull)sourceStoreFileName error:(NSError * _Nullable * _Null_unspecified)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSFetchRequest (SWIFT_EXTENSION(LCYCoreDataHelper))
+ (NSFetchRequest * _Nonnull)fetchRequestInContext:(NSString * _Nonnull)entityName context:(NSManagedObjectContext * _Nonnull)context;
- (void)sort:(NSString * _Nonnull)key ascending:(BOOL)ascending;
- (void)sortByAttributes:(NSArray<NSString *> * _Nonnull)attributes ascending:(BOOL)ascending;
- (id _Nullable)fetchFirstObject:(NSManagedObjectContext * _Nonnull)context;
@end


@interface NSManagedObject (SWIFT_EXTENSION(LCYCoreDataHelper))
- (BOOL)deleteEntityAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)deleteEntityInContext:(NSManagedObjectContext * _Nonnull)context error:(NSError * _Nullable * _Null_unspecified)error;
@end


@interface NSManagedObjectContext (SWIFT_EXTENSION(LCYCoreDataHelper))
@end


@interface NSManagedObjectContext (SWIFT_EXTENSION(LCYCoreDataHelper))

/// synchronously save context on the context's queue.
///
/// \param error exception
- (BOOL)saveContextAndWaitAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
@end


@interface NSNull (SWIFT_EXTENSION(LCYCoreDataHelper))
@end


@interface NSPersistentStoreCoordinator (SWIFT_EXTENSION(LCYCoreDataHelper))
@end

#pragma clang diagnostic pop
